name: Master Workflow - Build and Deploy to GHCR

on:
  push:
    branches: [ "master" ]

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Read package.json'
        uses: rexdefuror/read-package-json@v1.0.5

      - name: 'Build Image'
        run: |
          podman build . -t ghcr.io/ptrk25/${{ github.event.repository.name }}:v${{ env.PACKAGE_VERSION }}
          
      - name: 'Push to GHCR'
        run: |
          podman push ghcr.io/ptrk25/${{ github.event.repository.name }}:v${{ env.PACKAGE_VERSION }}
